name: jmascot
favicon: null
layout_spectrum: 0.49461616203188896
typography_spectrum: 0.13895882037468255
title: Master of Karate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3420785053167492
  lightness: 0.5879744538106024
  saturation: 0.13766070967540145
  rhythmicContrast: 0.982903165044263
purpose: []
